import type { IllnessDefinition, MapDefinition, MapId, PetKind, RoomDefinition, RoomKind, SkillId } from './types';

export const ROOM_DEFINITIONS: Record<RoomKind, RoomDefinition> = {
  exam: {
    kind: 'exam',
    title: 'Cozy Exam Room',
    shortTitle: 'Exam',
    description: 'Handles checkups, paw bumps, and first visits.',
    icon: '🩺',
    cost: 180,
    upkeep: 18,
    width: 2,
    height: 2,
    treatmentSeconds: 7,
    revenueBonus: 18,
    color: 0x80d8ff,
    accent: 0x18a0fb,
  },
  grooming: {
    kind: 'grooming',
    title: 'Fluffy Grooming Spa',
    shortTitle: 'Groom',
    description: 'Treats itchy coats and messy fur emergencies.',
    icon: '🫧',
    cost: 230,
    upkeep: 22,
    width: 2,
    height: 2,
    treatmentSeconds: 9,
    revenueBonus: 28,
    color: 0xfccde2,
    accent: 0xf06292,
  },
  lab: {
    kind: 'lab',
    title: 'Tiny Diagnostics Lab',
    shortTitle: 'Lab',
    description: 'Finds tummy bugs and mystery sniffles.',
    icon: '🧪',
    cost: 320,
    upkeep: 30,
    width: 2,
    height: 2,
    treatmentSeconds: 12,
    revenueBonus: 42,
    color: 0xb8f7d4,
    accent: 0x16a34a,
  },
  recovery: {
    kind: 'recovery',
    title: 'Sunny Recovery Ward',
    shortTitle: 'Rest',
    description: 'A calm place for nervous pets and sprained paws.',
    icon: '🌤️',
    cost: 280,
    upkeep: 26,
    width: 2,
    height: 2,
    treatmentSeconds: 10,
    revenueBonus: 35,
    color: 0xffe4a3,
    accent: 0xf59e0b,
  },
};

export const ILLNESSES: IllnessDefinition[] = [
  {
    id: 'wellness-check',
    title: 'Wellness Check',
    requiredRoom: 'exam',
    value: 58,
    patienceSeconds: 34,
  },
  {
    id: 'paw-bump',
    title: 'Paw Bump',
    requiredRoom: 'exam',
    value: 72,
    patienceSeconds: 30,
  },
  {
    id: 'itchy-coat',
    title: 'Itchy Coat',
    requiredRoom: 'grooming',
    value: 86,
    patienceSeconds: 38,
  },
  {
    id: 'muddy-fur',
    title: 'Muddy Fur Crisis',
    requiredRoom: 'grooming',
    value: 96,
    patienceSeconds: 36,
  },
  {
    id: 'tummy-bug',
    title: 'Tummy Bug',
    requiredRoom: 'lab',
    value: 132,
    patienceSeconds: 46,
  },
  {
    id: 'mystery-sniffles',
    title: 'Mystery Sniffles',
    requiredRoom: 'lab',
    value: 124,
    patienceSeconds: 44,
  },
  {
    id: 'sprained-hop',
    title: 'Sprained Hop',
    requiredRoom: 'recovery',
    value: 110,
    patienceSeconds: 42,
  },
  {
    id: 'nervous-visit',
    title: 'Nervous Visit',
    requiredRoom: 'recovery',
    value: 94,
    patienceSeconds: 40,
  },
];

export const PET_ICONS: Record<PetKind, string> = {
  dog: '🐶',
  cat: '🐱',
  rabbit: '🐰',
  parrot: '🦜',
};

export const PET_NAMES = [
  'Mochi',
  'Biscuit',
  'Miso',
  'Pixel',
  'Pumpkin',
  'Nimbus',
  'Tofu',
  'Pebble',
  'Clover',
  'Waffle',
  'Lulu',
  'Pickle',
];

export const STAFF_NAMES = [
  'Dr. Mira',
  'Nurse Jun',
  'Dr. Nova',
  'Tech Sam',
  'Nurse Pip',
  'Dr. Sol',
  'Tech Bea',
];

export const PET_KINDS: PetKind[] = ['dog', 'cat', 'rabbit', 'parrot'];

export interface SkillDefinition {
  id: SkillId;
  title: string;
  description: string;
  maxRank: number;
  icon: string;
}

export const SKILL_DEFINITIONS: Record<SkillId, SkillDefinition> = {
  calmHands: {
    id: 'calmHands',
    title: 'Calm Hands',
    description: 'Pets lose patience more slowly while assigned staff are on duty.',
    maxRank: 3,
    icon: '🫶',
  },
  fastDiagnosis: {
    id: 'fastDiagnosis',
    title: 'Fast Diagnosis',
    description: 'Treatment speed improves for every trained rank.',
    maxRank: 3,
    icon: '⚡',
  },
  sparkleCare: {
    id: 'sparkleCare',
    title: 'Sparkle Care',
    description: 'Rooms stay cleaner and recovery payouts rise slightly.',
    maxRank: 2,
    icon: '✨',
  },
  routingSense: {
    id: 'routingSense',
    title: 'Routing Sense',
    description: 'Patients move faster through the hospital corridors.',
    maxRank: 2,
    icon: '🧭',
  },
};

export const SKILL_ORDER: SkillId[] = ['fastDiagnosis', 'calmHands', 'sparkleCare', 'routingSense'];

export const MAX_ROOM_LEVEL = 3;

export const MAP_DEFINITIONS: Record<MapId, MapDefinition> = {
  gardenClinic: {
    id: 'gardenClinic',
    chapter: 1,
    unlockWave: 1,
    title: 'Garden Clinic',
    subtitle: 'Soft Opening',
    description: 'A compact neighborhood clinic with forgiving demand and short walking routes.',
    palette: {
      background: 0xf6fff9,
      border: 0xffffff,
      header: 0xd9f7ee,
      footer: 0xb8f0dc,
      route: 0x7ecbb7,
      accent: 0x18a0fb,
      waiting: 0xe5fff6,
    },
    entrance: { x: 1, y: 7 },
    exit: { x: 1, y: 7 },
    waitingSpots: [
      { x: 4, y: 4 },
      { x: 4, y: 5 },
      { x: 4, y: 6 },
      { x: 4, y: 7 },
      { x: 4, y: 8 },
      { x: 4, y: 9 },
    ],
    corridorRows: [7],
    corridorColumns: [1, 4],
    waitingArea: { x: 3, y: 4, width: 3, height: 6 },
    startingRooms: [
      { kind: 'exam', gridX: 7, gridY: 4 },
      { kind: 'recovery', gridX: 11, gridY: 4 },
    ],
    decorations: [
      { x: 6.25, y: 1.1 },
      { x: 15.85, y: 1.2 },
      { x: 16.1, y: 10.65 },
      { x: 2.7, y: 10.65 },
    ],
    spawnDelayMultiplier: 1,
    patienceMultiplier: 1,
    revenueMultiplier: 1,
    pressureMultiplier: 1,
    upkeepMultiplier: 1,
    urgentBias: 0,
    scoreMultiplier: 1,
  },
  downtownRescue: {
    id: 'downtownRescue',
    chapter: 2,
    unlockWave: 3,
    title: 'Downtown Rescue',
    subtitle: 'Busy City Intake',
    description: 'More urgent pets arrive from the city shelter, and queue pressure climbs faster.',
    palette: {
      background: 0xf7fbff,
      border: 0xdbeafe,
      header: 0xdbeafe,
      footer: 0xbfdbfe,
      route: 0x60a5fa,
      accent: 0x2563eb,
      waiting: 0xe0f2fe,
    },
    entrance: { x: 1, y: 6 },
    exit: { x: 1, y: 6 },
    waitingSpots: [
      { x: 5, y: 3 },
      { x: 5, y: 4 },
      { x: 5, y: 5 },
      { x: 5, y: 6 },
      { x: 5, y: 7 },
      { x: 5, y: 8 },
      { x: 8, y: 6 },
    ],
    corridorRows: [6, 9],
    corridorColumns: [1, 5, 8],
    waitingArea: { x: 4, y: 3, width: 3, height: 6 },
    startingRooms: [
      { kind: 'exam', gridX: 8, gridY: 3 },
      { kind: 'grooming', gridX: 12, gridY: 3 },
    ],
    decorations: [
      { x: 2.7, y: 1.2 },
      { x: 15.4, y: 1.3 },
      { x: 16.1, y: 9.9 },
      { x: 3.2, y: 10.6 },
      { x: 10.2, y: 10.4 },
    ],
    spawnDelayMultiplier: 0.86,
    patienceMultiplier: 0.94,
    revenueMultiplier: 1.08,
    pressureMultiplier: 1.12,
    upkeepMultiplier: 1.08,
    urgentBias: 0.06,
    scoreMultiplier: 1.12,
  },
  beachsideSpa: {
    id: 'beachsideSpa',
    chapter: 3,
    unlockWave: 5,
    title: 'Beachside Spa',
    subtitle: 'VIP Wellness Week',
    description: 'VIP owners expect cleaner rooms, better comfort, and premium treatment quality.',
    palette: {
      background: 0xfffbeb,
      border: 0xfef3c7,
      header: 0xfde68a,
      footer: 0xfcd34d,
      route: 0x38bdf8,
      accent: 0xf59e0b,
      waiting: 0xfef9c3,
    },
    entrance: { x: 1, y: 8 },
    exit: { x: 1, y: 8 },
    waitingSpots: [
      { x: 4, y: 5 },
      { x: 5, y: 5 },
      { x: 6, y: 5 },
      { x: 4, y: 6 },
      { x: 5, y: 6 },
      { x: 6, y: 6 },
      { x: 5, y: 7 },
    ],
    corridorRows: [5, 8],
    corridorColumns: [1, 6, 10],
    waitingArea: { x: 4, y: 4, width: 4, height: 4 },
    startingRooms: [
      { kind: 'exam', gridX: 9, gridY: 4 },
      { kind: 'grooming', gridX: 13, gridY: 4 },
      { kind: 'recovery', gridX: 9, gridY: 8 },
    ],
    decorations: [
      { x: 3.1, y: 1.1 },
      { x: 15.7, y: 1.3 },
      { x: 16.1, y: 10.4 },
      { x: 2.7, y: 10.65 },
      { x: 12.4, y: 10.5 },
    ],
    spawnDelayMultiplier: 0.78,
    patienceMultiplier: 0.9,
    revenueMultiplier: 1.18,
    pressureMultiplier: 1.2,
    upkeepMultiplier: 1.16,
    urgentBias: 0.03,
    scoreMultiplier: 1.24,
  },
  mountainEmergency: {
    id: 'mountainEmergency',
    chapter: 4,
    unlockWave: 7,
    title: 'Mountain Emergency',
    subtitle: 'Storm Season Triage',
    description: 'Long routes, fast emergencies, and expensive upkeep make this the hardest map.',
    palette: {
      background: 0xf1f5f9,
      border: 0xcbd5e1,
      header: 0xdbe4ee,
      footer: 0x94a3b8,
      route: 0x818cf8,
      accent: 0x7c3aed,
      waiting: 0xe0e7ff,
    },
    entrance: { x: 1, y: 10 },
    exit: { x: 1, y: 10 },
    waitingSpots: [
      { x: 6, y: 2 },
      { x: 6, y: 3 },
      { x: 6, y: 4 },
      { x: 7, y: 4 },
      { x: 8, y: 4 },
      { x: 8, y: 5 },
      { x: 8, y: 6 },
      { x: 9, y: 6 },
    ],
    corridorRows: [4, 7, 10],
    corridorColumns: [1, 6, 9, 13],
    waitingArea: { x: 5, y: 2, width: 5, height: 5 },
    startingRooms: [
      { kind: 'exam', gridX: 10, gridY: 2 },
      { kind: 'lab', gridX: 14, gridY: 2 },
      { kind: 'recovery', gridX: 10, gridY: 7 },
    ],
    decorations: [
      { x: 3.2, y: 1.1 },
      { x: 15.8, y: 1.1 },
      { x: 16.2, y: 10.6 },
      { x: 2.7, y: 10.55 },
      { x: 12.8, y: 10.5 },
      { x: 4.8, y: 8.8 },
    ],
    spawnDelayMultiplier: 0.68,
    patienceMultiplier: 0.82,
    revenueMultiplier: 1.28,
    pressureMultiplier: 1.34,
    upkeepMultiplier: 1.28,
    urgentBias: 0.12,
    scoreMultiplier: 1.42,
  },
};

export const MAP_ORDER: MapId[] = ['gardenClinic', 'downtownRescue', 'beachsideSpa', 'mountainEmergency'];
